apiVersion: v1
kind: Pod
metadata:
  name: kafka-java-console-schema-sample
  namespace: default
spec:
  containers:
  - image: ibmcom/kafka-java-console-schema-sample:latest
    imagePullPolicy: Always
    name: java-sample
    env:
    - name: VCAP_SERVICES
      valueFrom:
          secretKeyRef:
            name: eventstreams-binding
            key: binding
