apiVersion: v1
kind: Pod
metadata:
  name: kafka-nodejs-console-sample
  namespace: default
spec:
  containers:
  - image: ibmcom/kafka-nodejs-console-sample:latest
    imagePullPolicy: IfNotPresent
    name: nodejs-sample
    env:
    - name: VCAP_SERVICES
      valueFrom:
          secretKeyRef:
            name: eventstreams-binding
            key: binding